### ISSUE TITLE
Is the package itself ever installed in the pipenv environment? Why?

### ISSUE THREAD

**Issue by stefanoborini** [elgertam/cookiecutter-pipenv#13]
I am trying to understand a pipenv bug, and I took your cookiecutter as verification. You never seem to install the created package itself in editable mode in the generated pipenv environment. Is this intentional or just an accident?

**Comment by elgertam** [comment]
@stefanoborini This is a good question. I experimented with that a while ago, and I ran into some odd issues with Pipenv throwing errors or behaving erratically when I did so. I can't remember all of the details, but I ultimately decided to drop it and allow users to specify how they wanted to install the package for themselves, whether through `python setup.py develop`, `pip install -e .` or by adding `<hash> = {path = ".",editable = true}` to the Pipfile.

I personally prefer the latter (if someone's using pipenv, I figure they wouldn't defer to other tools - too much complication or confusion). Now that you bring it up, I may try experimenting with this again. I could be getting some of the details very wrong, since it's been so long since I experimented this way.

Does this answer your question?

**Comment by elgertam** [comment]
@stefanoborini I ended up experimenting with this today, and had no further issues installing the generated package in editable mode. I did notice some issues when running `tox` on a freshly-created package generated using this template, so I have some additional work to do there for painlessly supporting 2.7 and 3.5. (This should be possible if Pipenv supports PEP 508 as the docs claim.)

**Comment by gusennan** [comment]
I'm using this cookie cutter template, thanks for sharing it.

I have a very similar question.  I've created a minimal example using all of the default selections for this template, and in `cli.py` try to `from python_boilerplate import test_fn`, after defining said function in `python_boilerplate.py`. This error is:

```
(python_boilerplate) nsg@rasputin ~/t/python_boilerplate> python python_boilerplate/cli.py
Traceback (most recent call last):
  File "python_boilerplate/cli.py", line 7, in <module>
    from .python_boilerplate import test_fn
```

In contrast, when I do: 
```
(python_boilerplate) nsg@rasputin ~/t/python_boilerplate> python -m python_boilerplate.cli
Replace this message by putting your code into python_boilerplate.cli.main
See click documentation at http://click.pocoo.org/
(python_boilerplate) nsg@rasputin ~/t/python_boilerplate> 
```
It works as intended. Is this the expected behavior?

**Comment by elgertam** [comment]
@gusennan The behavior depends on how you the user writes the import. This is dictated by Python itself (Python 3 specifically), and nothing in my project (or in `cookiecutter-pypackage`, which this is based on).

I set up my `python_boilerplate/cli.py` file to have the following like as you:

```python
from .python_boilerplate import test_fn
```

When invoking a relative import in Python 3, the import must take place within a package context. If it does not, the program will throw an error: `ModuleNotFoundError: No module named '__main__.python_boilerplate'; '__main__' is not a package`. This is what I see when I invoke the file simply as a script:

```bash
$ python python_boilerplate/cli.py
Traceback (most recent call last):
  File "python_boilerplate/cli.py", line 6, in <module>
    from .python_boilerplate import test_fn
ModuleNotFoundError: No module named '__main__.python_boilerplate'; '__main__' is not a package
```

When I run it as a module `python -m python_boilerplate.cli`, I get the expected CLI output.

However, let's suppose I change the import in `cli.py`:

```python
from python_boilerplate import test_fn
```

Then when I run it as a script, I get:

```bash
$ python python_boilerplate/cli.py 
Replace this message by putting your code into python_boilerplate.cli.main
See click documentation at http://click.pocoo.org/
```

As a module (long paths truncated):

```bash
$ python -m python_boilerplate.cli
Traceback (most recent call last):
  File ".../python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File ".../python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File ".../python_boilerplate/python_boilerplate/cli.py", line 6, in <module>
    from python_boilerplate import test_fn
ImportError: cannot import name 'test_fn' from 'python_boilerplate' (.../python_boilerplate/python_boilerplate/__init__.py)
```

So, **TL;DR: I leave it up to the user.**

I think (and this is just my opinion) that the better choice is to use the module syntax rather than executing one-off scripts. I also set the `entry_points` argument in `setup.py`'s `setup()` function, which will create an executable in the virtualenv in which the generated package is installed (e.g. `<path/to/venv>/bin/python_boilerplate`). Using that feature allows a CLI tool to be easily installed using, for example, the pipx tool (https://github.com/pipxproject/pipx).

I hope this answers the question.

**Comment by gusennan** [comment]
Thanks so much for clarifying!
